# Generated by Django 4.0.4 on 2022-05-09 17:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=250, verbose_name='Тема')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ежедневный матерял',
                'verbose_name_plural': 'Ежедневный матерял',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Названия')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Домашняя работа')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Домашняя работа',
                'verbose_name_plural': 'Домашняя работа',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Фото')),
                ('tel_num', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефонный номер')),
                ('year_data', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('password', models.CharField(blank=True, max_length=250, null=True, verbose_name='Пароль')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студент',
            },
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Учебный Год',
                'verbose_name_plural': 'Учебный Год',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Фото')),
                ('tel_num', models.CharField(max_length=250, verbose_name='Телефонный номер')),
                ('year_data', models.PositiveIntegerField(verbose_name='Год рождения')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователь',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.groups', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студент группа',
                'verbose_name_plural': 'Студент группа',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('daily_material', models.ManyToManyField(to='project.dailymaterial', verbose_name='Ежедневный матерял')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Урок',
            },
        ),
        migrations.CreateModel(
            name='HomeWorkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_home_work', ckeditor.fields.RichTextField(verbose_name='Готовая домашняя работа')),
                ('ball', models.PositiveIntegerField(verbose_name='Бал')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('home_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.homework', verbose_name='Домашняя работа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Готовая домашняя работа',
                'verbose_name_plural': 'Готовая домашняя работа',
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='home_work',
            field=models.ManyToManyField(to='project.lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='homework',
            name='studentGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.studentgroup', verbose_name='Студент группа'),
        ),
        migrations.AddField(
            model_name='groups',
            name='study_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.studyyear', verbose_name='Учебный Год'),
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.teacher', verbose_name='Преподователь'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Коментарии',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_student', models.CharField(choices=[('Непришел', '-'), ('Пришел', '+')], max_length=300, verbose_name='Отметка')),
                ('create_data', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('studentGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.studentgroup', verbose_name='Студент группа')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
    ]
